# Generated by Django 6.0.2 on 2026-03-30 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_aula', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=200)),
                ('palestrante', models.CharField(max_length=100)),
                ('carga_horaria', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_evento', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('local', models.CharField(choices=[('AUDITORIO HSI', 'hsi'), ('AUDITORIO ADM CENTRAL', 'pupileira')], max_length=50)),
                ('status', models.CharField(choices=[('FINALIZADO', 'finalizado'), ('CANCELADO', 'cancelado'), ('MARCADO', 'marcado'), ('ANDAMENTO', 'andamento')], max_length=50)),
                ('participantes', models.JSONField(blank=True, default=list)),
                ('horario_final', models.TimeField(blank=True, null=True)),
                ('aulas', models.ManyToManyField(related_name='aulas', to='events.aula')),
                ('usuario_cadastrante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
