# Generated by Django 6.0.2 on 2026-03-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_aula', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=200)),
                ('palestrante', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField()),
            ],
        ),
    ]
