# Generated by Django 6.0.2 on 2026-03-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_evento', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('local', models.CharField(choices=[('AUDITORIO HSI', 'hsi'), ('AUDITORIO ADM CENTRAL', 'pupileira')], max_length=50)),
                ('status', models.CharField(choices=[('FINALIZADO', 'finalizado'), ('CANCELADO', 'cancelado'), ('MARCADO', 'marcado')], max_length=50)),
                ('participantes', models.JSONField(blank=True, default=list)),
                ('aulas', models.ManyToManyField(related_name='aulas', to='events.aula')),
            ],
        ),
    ]
