# Generated by Django 6.0.2 on 2026-03-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_treinamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamento',
            name='status',
            field=models.CharField(choices=[('FINALIZADO', 'finalizado'), ('CANCELADO', 'cancelado'), ('MARCADO', 'marcado'), ('ANDAMENTO', 'andamento')], max_length=50),
        ),
    ]
