# Generated by Django 6.0.2 on 2026-04-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_aula_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='horario_final_aula',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aula',
            name='horario_inicial_aula',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
