# Generated by Django 6.0.2 on 2026-03-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_treinamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamento',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
