# Generated by Django 6.0.2 on 2026-03-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_treinamento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='carga_horaria',
            field=models.TimeField(),
        ),
    ]
