# Generated by Django 6.0.2 on 2026-03-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_aula_carga_horaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinamento',
            name='horario_final',
            field=models.TimeField(null=True),
        ),
    ]
