# Generated by Django 6.0.2 on 2026-03-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_treinamento_horario_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamento',
            name='horario_final',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
