# Generated by Django 6.0.2 on 2026-03-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_treinamento_horario_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinamento',
            name='usuario_cadastrante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
