version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: listggp_postgres
    restart: always
    environment:
      POSTGRES_DB: listggp_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django_app:
    build: .
    container_name: listggp_web
    ports:
      # Expõe a porta 443 (padrão HTTPS) do seu servidor apontando para a 8000 do contêiner
      - "443:8000" 
    volumes:
      # Copia o código do seu Windows para dentro do Docker
      - .:/app
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 --threads 2 --certfile=/app/cert.crt --keyfile=/app/cert.key config.wsgi:application
volumes:
  postgres_data: