services:
  db:
    image: postgres:15-alpine
    container_name: listggp_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django_app:
    build: .
    container_name: listggp_web
    ports:
      - "443:8000" 
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 --threads 8 --certfile=/app/cert.crt --keyfile=/app/cert.key config.wsgi:application
volumes:
  postgres_data: