# Generated by Django 6.0.2 on 2026-06-23 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_certificado', models.CharField(max_length=150)),
                ('carga_horaria', models.TimeField()),
                ('palestrante', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('APROVADO', 'aprovado'), ('REPROVADO', 'reprovado'), ('AGUARDANDO ANÁLISE', 'aguardando análise')], max_length=50)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
