# Generated by Django 6.0.2 on 2026-06-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='status',
            field=models.CharField(choices=[('APROVADO', 'aprovado'), ('REPROVADO', 'reprovado'), ('AGUARDANDO ANÁLISE', 'aguardando análise'), ('CANCELADO', 'cancelado')], max_length=50),
        ),
    ]
